name: omm_admin
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI + Icons + Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  provider: ^6.1.2

  # Media & Files
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  file_picker: ^10.3.3

  # Navigation & UI extras
  curved_navigation_bar: ^1.0.6
  carousel_slider: ^5.1.1
  flutter_speed_dial: ^7.0.0
  flutter_slidable: ^4.0.1
  lottie: ^3.3.1

  # Utils
  intl: ^0.20.2
  fl_chart: ^1.1.0
  csv: ^6.0.0
  share_plus: ^12.0.0
  uuid: ^4.5.1
  http: ^1.5.0
  shared_preferences: ^2.5.3
  image: ^4.1.3  # For image compression and processing
  mobile_scanner: ^7.1.3
  socket_io_client: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gifs/images/loginimage.png
